# Generated by Django 4.2.2 on 2023-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=255, null=True, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=255, null=True, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(verbose_name='Продолжительность'),
        ),
    ]
