# Generated by Django 4.2.2 on 2023-07-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='people',
            field=models.PositiveIntegerField(verbose_name='Количество человек'),
        ),
    ]
