# Generated by Django 4.2.2 on 2023-07-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_artist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Мастера'},
        ),
    ]
