# Generated by Django 4.2.2 on 2023-07-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_artist_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
    ]
